server.port=8083
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USER}
spring.datasource.password=${LOCAL_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.configs.default.ignore-exceptions[0]=org.springframework.web.client.HttpClientErrorException
resilience4j.circuitbreaker.configs.default.ignore-exceptions[1]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.catalog-get.base-config=default
resilience4j.circuitbreaker.instances.catalog-reserve.base-config=default
resilience4j.circuitbreaker.instances.users-get.base-config=default