server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**,/api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=catalog-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://catalog-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/animals/**,/api/v1/shelters/**

spring.cloud.gateway.server.webmvc.routes[2].id=adoption-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://adoption-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/applications/**