services:

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - microservices-net

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    volumes:
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  mongo-db:
    image: mongo:8
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: animals
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - microservices-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    env_file:
      - kafka.env
    networks:
      - microservices-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - microservices-net

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - api-gateway.env
    depends_on:
      consul:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - microservices-net

  config-server:
    build: ./config-server
    container_name: config-server
    env_file:
      - config-server.env
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - consul
    networks:
      - microservices-net

  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - user-service.env
    depends_on:
      postgres-db:
        condition: service_healthy
      consul:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - microservices-net

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    env_file:
      - catalog-service.env
    depends_on:
      postgres-db:
        condition: service_healthy
      mongo-db:
        condition: service_healthy
      minio:
        condition: service_started
      consul:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - microservices-net

  adoption-service:
    build: ./adoption-service
    container_name: adoption-service
    env_file:
      - adoption-service.env
    depends_on:
      postgres-db:
        condition: service_healthy
      consul:
        condition: service_started
      config-server:
        condition: service_healthy
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  pgdata:
  mongo_data:
  minio_data: