services:
  consul:
    image: hashicorp/consul:latest
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  minio:
    image: quay.io/minio/minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345

    volumes:
      - ./data:/data

    command: server /data --console-address ":9001"

    restart: unless-stopped

  mongo:
    image: mongo:8

    ports:
       - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: animals

    volumes:
        - mongo_data:/data/db

    restart: unless-stopped

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    env_file:
      - kafka.env
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
   mongo_data: