databaseChangeLog:

  - changeSet:
      id: 001-application-revoked-outbox-table
      author: victoria

      changes:

        - createTable:
            schemaName: outbox
            tableName: application_revoked_outbox

            columns:

              - column:
                  name: event_id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: animal_id
                  type: BIGINT
                  constraints:
                    nullable: false

              - column:
                  name: application_id
                  type: BIGINT
                  constraints:
                    nullable: false

              - column:
                  name: status
                  type: VARCHAR(20)
                  constraints:
                    nullable: false

              - column:
                  name: occurred_at
                  type: TIMESTAMP WITH TIME ZONE
                  constraints:
                    nullable: false

              - column:
                  name: processing_started_at
                  type: TIMESTAMP WITH TIME ZONE

              - column:
                  name: published_at
                  type: TIMESTAMP WITH TIME ZONE

        - createIndex:
            schemaName: outbox
            tableName: application_revoked_outbox
            indexName: idx_application_revoked_status_occured_at

            columns:
              - column:
                  name: status

              - column:
                  name: occurred_at

        - createIndex:
            schemaName: outbox
            tableName: application_revoked_outbox
            indexName: idx_application_revoked_status_processing_started_at

            columns:
              - column:
                  name: status

              - column:
                  name: processing_started_at